import type { ErwinRow } from "./data.store";

export const MOCK_ERWIN_DATA: ErwinRow[] = [
	{
		type: "Entity/Table",
		prop: "",
		change: "A",
		view: "L/P",
		leftModel: "CLI",
		rightModel: "CLI_PF",
		indent: 4,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "A",
		view: "",
		leftModel: "Cliente",
		rightModel: "Cliente Pessoa Fisica",
		indent: 6,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "A",
		view: "",
		leftModel: "CLI",
		rightModel: "CLI_PF",
		indent: 6,
	},
	{
		type: "Description",
		prop: "",
		change: "A",
		view: "",
		leftModel: "Cliente de interesse da intituição",
		rightModel: "Cliente Pessoa Fisica cadastrado",
		indent: 6,
	},
	{
		type: "Comment",
		prop: "",
		change: "A",
		view: "",
		leftModel: "Cliente de interesse da intituição [Calculated]",
		rightModel: "Cliente Pessoa Fisica cadastrado [Calculated]",
		indent: 6,
	},
	{
		type: "Max Rows",
		prop: "",
		change: "I",
		view: "",
		leftModel: "10000000",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Growth By",
		prop: "",
		change: "I",
		view: "",
		leftModel: "10000",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Initial Rows",
		prop: "",
		change: "I",
		view: "",
		leftModel: "0",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Atributes/Columns",
		prop: "",
		change: "",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 8,
	},
	{
		type: "Atribute/Column",
		prop: "",
		change: "A",
		view: "L/P",
		leftModel: "NR_PTR",
		rightModel: "NR_PTR",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "A",
		view: "",
		leftModel: "Numero da Partição",
		rightModel: "Numero da Particao",
		indent: 12,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "A",
		view: "",
		leftModel: "true",
		rightModel: "false",
		indent: 12,
	},
	{
		type: "Theme",
		prop: "",
		change: "I",
		view: "",
		leftModel: "A.Fisico",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Atribute/Column",
		prop: "",
		change: "I",
		view: "L/P",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo Operação",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Logical Datatype",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CHAR(8)",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Datatype",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CHAR(8) [Calculated]",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Null Option",
		prop: "",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "Not Null",
		indent: 12,
	},
	{
		type: "Parent Domain",
		prop: "",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "String",
		indent: 12,
	},
	{
		type: "Description",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Comment",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama [Calculated]",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "false",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "false",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Theme",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Corporativa",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Atribute/Column",
		prop: "",
		change: "E",
		view: "L/P",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo Produto",
		indent: 12,
	},
	{
		type: "Logical Datatype",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Integer",
		indent: 12,
	},
	{
		type: "Physical Datatype",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Integer [Calculated]",
		indent: 12,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 12,
	},
	{
		type: "Description",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo do Produto da Empresa",
		indent: 12,
	},
	{
		type: "Comment",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo do Produto da Empresa [Calculated]",
		indent: 12,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "false",
		indent: 12,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "false",
		indent: 12,
	},
	{
		type: "Theme",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Corporativa",
		indent: 12,
	},
	{
		type: "Null Option",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Not Null",
		indent: 12,
	},
	{
		type: "Parent Domain",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Number",
		indent: 12,
	},
	{
		type: "Foreign Keys",
		prop: "",
		change: "",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 8,
	},
	{
		type: "Foreign Key",
		prop: "",
		change: "I",
		view: "FK",
		leftModel: "FK_CLI_02",
		rightModel: "",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "FK_CLI_02",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Keys/Indexes",
		prop: "",
		change: "",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 8,
	},
	{
		type: "Key/Index",
		prop: "",
		change: "I",
		view: "IX",
		leftModel: "IX_CLI_02",
		rightModel: "",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Type",
		prop: "",
		change: "I",
		view: "",
		leftModel: "FK",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Entity/Table",
		prop: "",
		change: "I",
		view: "L/P",
		leftModel: "OPR",
		rightModel: "",
		indent: 4,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Operação",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "OPR",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Description",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Operação do sistama",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Comment",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Operação do sistama [Calculated]",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "true",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "false",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Theme",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Corporativa",
		rightModel: "",
		indent: 6,
	},
	{
		type: "Atributes/Columns",
		prop: "",
		change: "",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 8,
	},
	{
		type: "Atribute/Column",
		prop: "",
		change: "I",
		view: "L/P",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo Operação",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Logical Datatype",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CHAR(8)",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Datatype",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CHAR(8) [Calculated]",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "I",
		view: "",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Null Option",
		prop: "",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "Not Null",
		indent: 12,
	},
	{
		type: "Parent Domain",
		prop: "",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "String",
		indent: 12,
	},
	{
		type: "Description",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Comment",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama [Calculated]",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "false",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "I",
		view: "",
		leftModel: "false",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Theme",
		prop: "",
		change: "I",
		view: "",
		leftModel: "Corporativa",
		rightModel: "",
		indent: 12,
	},
	{
		type: "Entity/Table",
		prop: "",
		change: "E",
		view: "L/P",
		leftModel: "",
		rightModel: "PRD",
		indent: 4,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Produto",
		indent: 6,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "PRD",
		indent: 6,
	},
	{
		type: "Description",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Produto da Empresa",
		indent: 6,
	},
	{
		type: "Comment",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Produto da Empresa [Calculated]",
		indent: 6,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "true",
		indent: 6,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "false",
		indent: 6,
	},
	{
		type: "Theme",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Corporativa",
		indent: 6,
	},
	{
		type: "Atributes/Columns",
		prop: "",
		change: "",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 8,
	},
	{
		type: "Atribute/Column",
		prop: "",
		change: "E",
		view: "L/P",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 10,
		isHeader: true,
	},
	{
		type: "Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo Produto",
		indent: 12,
	},
	{
		type: "Logical Datatype",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Integer",
		indent: 12,
	},
	{
		type: "Physical Datatype",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Integer [Calculated]",
		indent: 12,
	},
	{
		type: "Physical Name",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 12,
	},
	{
		type: "Description",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo do Produto da Empresa",
		indent: 12,
	},
	{
		type: "Comment",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo do Produto da Empresa [Calculated]",
		indent: 12,
	},
	{
		type: "Logical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "false",
		indent: 12,
	},
	{
		type: "Physical Only",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "false",
		indent: 12,
	},
	{
		type: "Theme",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Corporativa",
		indent: 12,
	},
	{
		type: "Null Option",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Not Null",
		indent: 12,
	},
	{
		type: "Parent Domain",
		prop: "",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Number",
		indent: 12,
	},
];
