import type { ErwinRow } from "./data.store";

/**
 * Mock data representing a real-world Erwin comparison report.
 * Indentation: 4 spaces = 1 Level (consistent with AGENTS.md requirements)
 * Status Hoisting applied: Exclusão > Inclusão > Alteração > Sem Mudança
 */
export const MOCK_ERWIN_DATA: ErwinRow[] = [
	// TABLE 1: CLI / CLI_PF (Altered)
	{
		type: "Entity/Table: CLI / CLI_PF",
		prop: "CLI_PF",
		change: "A",
		view: "L/P",
		leftModel: "CLI",
		rightModel: "CLI_PF",
		indent: 4, // Level 1
		isHeader: true,
	},
	{
		type: "        Name",
		prop: "CLI_PF",
		change: "A",
		view: "",
		leftModel: "Cliente",
		rightModel: "Cliente Pessoa Fisica",
		indent: 8, // Level 2
	},
	{
		type: "        Physical Name",
		prop: "CLI_PF",
		change: "A",
		view: "",
		leftModel: "CLI",
		rightModel: "CLI_PF",
		indent: 8,
	},
	{
		type: "        Description",
		prop: "CLI_PF",
		change: "A",
		view: "",
		leftModel: "Cliente de interesse da intituição",
		rightModel: "Cliente Pessoa Fisica cadastrado",
		indent: 8,
	},
	{
		type: "        Comment",
		prop: "CLI_PF",
		change: "A",
		view: "",
		leftModel: "Cliente de interesse da intituição [Calculated]",
		rightModel: "Cliente Pessoa Fisica cadastrado [Calculated]",
		indent: 8,
	},
	{
		type: "        Max Rows",
		prop: "CLI_PF",
		change: "I",
		view: "",
		leftModel: "10000000",
		rightModel: "",
		indent: 8,
	},
	{
		type: "        Growth By",
		prop: "CLI_PF",
		change: "I",
		view: "",
		leftModel: "10000",
		rightModel: "",
		indent: 8,
	},
	{
		type: "        Initial Rows",
		prop: "CLI_PF",
		change: "I",
		view: "",
		leftModel: "0",
		rightModel: "",
		indent: 8,
	},

	// COLUMNS GROUP
	{
		type: "            Atributes/Columns",
		prop: "CLI_PF",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 12, // Level 3
	},

	// COLUMN 1: NR_PTR (Altered + Inclusion) -> Hoisted to I
	{
		type: "                Atribute/Column: NR_PTR",
		prop: "NR_PTR",
		change: "I",
		view: "L/P",
		leftModel: "NR_PTR",
		rightModel: "NR_PTR",
		indent: 16, // Level 4
		isHeader: true,
	},
	{
		type: "                    Name",
		prop: "NR_PTR",
		change: "A",
		view: "",
		leftModel: "Numero da Partição",
		rightModel: "Numero da Particao",
		indent: 20, // Level 5
	},
	{
		type: "                    Physical Only",
		prop: "NR_PTR",
		change: "A",
		view: "",
		leftModel: "true",
		rightModel: "false",
		indent: 20,
	},
	{
		type: "                    Theme",
		prop: "NR_PTR",
		change: "I",
		view: "",
		leftModel: "A.Fisico",
		rightModel: "",
		indent: 20,
	},

	// COLUMN 2: CD_OPR (Inclusion)
	{
		type: "                Atribute/Column: CD_OPR",
		prop: "CD_OPR",
		change: "I",
		view: "L/P",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 16,
		isHeader: true,
	},
	{
		type: "                    Name",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "Codigo Operação",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Logical Datatype",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "CHAR(8)",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Physical Datatype",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "CHAR(8) [Calculated]",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Physical Name",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "CD_OPR",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Description",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Comment",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "Codigo da Operação do sistama [Calculated]",
		rightModel: "",
		indent: 20,
	},
	{
		type: "                    Theme",
		prop: "CD_OPR",
		change: "I",
		view: "",
		leftModel: "Corporativa",
		rightModel: "",
		indent: 20,
	},

	// COLUMN 3: CD_PRD (Exclusion)
	{
		type: "                Atribute/Column: CD_PRD",
		prop: "CD_PRD",
		change: "E",
		view: "L/P",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 16,
		isHeader: true,
	},
	{
		type: "                    Name",
		prop: "CD_PRD",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Codigo Produto",
		indent: 20,
	},
	{
		type: "                    Physical Name",
		prop: "CD_PRD",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "CD_PRD",
		indent: 20,
	},
	{
		type: "                    Null Option",
		prop: "CD_PRD",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Not Null",
		indent: 20,
	},

	// FOREIGN KEYS GROUP
	{
		type: "            Foreign Keys",
		prop: "CLI_PF",
		change: "I",
		view: "",
		leftModel: "",
		rightModel: "",
		indent: 12,
	},
	{
		type: "                Foreign Key: FK_CLI_02",
		prop: "FK_CLI_02",
		change: "I",
		view: "",
		leftModel: "FK_CLI_02",
		rightModel: "",
		indent: 16,
		isHeader: true,
	},
	{
		type: "                    Name",
		prop: "FK_CLI_02",
		change: "I",
		view: "",
		leftModel: "FK_CLI_02",
		rightModel: "",
		indent: 20,
	},

	// TABLE 2: OPR (Inclusion)
	{
		type: "Entity/Table: OPR",
		prop: "OPR",
		change: "I",
		view: "L/P",
		leftModel: "OPR",
		rightModel: "",
		indent: 4,
		isHeader: true,
	},
	{
		type: "        Name",
		prop: "OPR",
		change: "I",
		view: "",
		leftModel: "Operação",
		rightModel: "",
		indent: 8,
	},
	{
		type: "        Logical Only",
		prop: "OPR",
		change: "I",
		view: "",
		leftModel: "true",
		rightModel: "",
		indent: 8,
	},

	// TABLE 3: PRD (Exclusion)
	{
		type: "Entity/Table: PRD",
		prop: "PRD",
		change: "E",
		view: "L/P",
		leftModel: "",
		rightModel: "PRD",
		indent: 4,
		isHeader: true,
	},
	{
		type: "        Name",
		prop: "PRD",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "Produto",
		indent: 8,
	},
	{
		type: "        Physical Name",
		prop: "PRD",
		change: "E",
		view: "",
		leftModel: "",
		rightModel: "PRD",
		indent: 8,
	},
];
