import { INDENT_SIZE, type ModelObject } from '../types.js';

export const sampleData: ModelObject = {
  id: {
    level: 1,
    spaces: 1 * INDENT_SIZE,
    type: 'Model',
    left: 'XXX - Oracle',
    right: 'Model_1',
  },
  properties: [
    {
      level: 2,
      spaces: 2 * INDENT_SIZE,
      type: 'Name',
      left: 'XXX - Oracle',
      right: 'Model_1',
    },
    {
      level: 2,
      spaces: 2 * INDENT_SIZE,
      type: 'Author',
      left: 'Company A',
      right: 'Company A',
    },
  ],
  children: {
    Domains: [
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Domain',
          left: 'Number',
          right: 'Number',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'Number',
            right: 'Number',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Logical Datatype',
            left: 'Integer',
            right: 'Smallint',
          },
        ],
      },
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Domain',
          left: 'String',
          right: 'String',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'String',
            right: 'String',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Logical Datatype',
            left: 'VARCHAR(20)',
            right: 'VARCHAR(255)',
          },
        ],
      },
    ],
    'Subject Areas': [
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Subject Area',
          left: 'Main',
          right: 'Main',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Members',
            left: 'CLI,OPR,USU',
            right: 'CLI_PF,PRD,USU',
          },
        ],
        children: {
          'ER Diagrams': [
            {
              id: {
                level: 4,
                spaces: 4 * INDENT_SIZE,
                type: 'ER Diagram',
                left: 'Main Diagram',
                right: 'Main Diagram',
              },
              properties: [
                {
                  level: 5,
                  spaces: 5 * INDENT_SIZE,
                  type: 'Members',
                  left: 'CLI,OPR,USU',
                  right: 'CLI_PF,PRD,USU',
                },
              ],
            },
          ],
        },
      },
    ],
    Collections: [
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Collection',
          left: 'DOC',
          right: 'DOC',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'Document',
            right: 'Document Files',
          },
        ],
        children: {
          Fields: [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Field',
                left: 'NM_DOC',
                right: 'NM_DOC_FL',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: 'NM_DOC',
                  right: 'NM_DOC_FL',
                },
              ],
              children: {
                Fields: [
                  {
                    id: {
                      level: 7,
                      spaces: 7 * INDENT_SIZE,
                      type: 'Field',
                      left: 'NM_DOC',
                      right: 'NM_DOC_FL',
                    },
                    properties: [
                      {
                        level: 8,
                        spaces: 8 * INDENT_SIZE,
                        type: 'Physical Name',
                        left: 'NM_DOC',
                        right: 'NM_DOC_FL',
                      },
                    ],
                  },
                ],
              },
            },
          ],
        },
      },
    ],
    'Entities/Tables': [
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Entity/Table',
          left: 'CLI',
          right: 'CLI_PF',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Column Order List',
            left: 'NR_PTR,CD_PRD,Column1, Column2, Column3, Column4, Column5, Column6, Column7, Column8, Column9, Column10, Column11, Column12, Column13, Column14, Column15, Column16, Column17, Column18, Column19, Column20',
            right:
              'NR_PTR,CD_OPR,Column1, Column2, Column3, Column4, Column5, Column6, Column7, Column8, Column9, Column10, Column11, Column12, Column13, Column14, Column15, Column16, Column17, Column18, Column19, Column20',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'Client',
            right: 'Individual Client',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Name',
            left: 'CLI',
            right: 'CLI_PF',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Description',
            left: 'Client of interest to the institution',
            right: 'Registered Individual Client',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Comment',
            left: 'Client of interest to the institution [Calculated]',
            right: 'Registered Individual Client [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Max Rows',
            left: '10000000',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Growth By',
            left: '10000',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Initial Rows',
            left: '0',
            right: '',
          },
        ],
        children: {
          'Attributes/Columns': [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: 'NR_PTR',
                right: 'NR_PTR',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: 'Partition Number',
                  right: 'Partition Number',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: 'true',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: 'A.Physical',
                  right: '',
                },
              ],
            },
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: 'CD_OPR',
                right: '',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: 'Operation Code',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Datatype',
                  left: 'CHAR(8)',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Datatype',
                  left: 'CHAR(8) [Calculated]',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: 'CD_OPR',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Null Option',
                  left: 'Not Null',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Parent Domain',
                  left: 'String',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Description',
                  left: 'System Operation Code',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Comment',
                  left: 'System Operation Code [Calculated]',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Only',
                  left: 'false',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: 'false',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: 'Corporate',
                  right: '',
                },
              ],
            },
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: '',
                right: 'CD_PRD',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: '',
                  right: 'Product Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Datatype',
                  left: '',
                  right: 'Integer',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Datatype',
                  left: '',
                  right: 'Integer [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: '',
                  right: 'CD_PRD',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Description',
                  left: '',
                  right: 'Company Product Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Comment',
                  left: '',
                  right: 'Company Product Code [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Only',
                  left: '',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: '',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: '',
                  right: 'Corporate',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Null Option',
                  left: '',
                  right: 'Not Null',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Parent Domain',
                  left: '',
                  right: 'Number',
                },
              ],
            },
          ],
          Relationships: [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Relationship',
                left: 'FK_CLI_02',
                right: '',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: 'FK_CLI_02',
                  right: '',
                },
              ],
            },
          ],
          'Keys Groups/Indexes': [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Key Group/Index',
                left: 'IX_CLI_02',
                right: '',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Type',
                  left: 'FK',
                  right: '',
                },
              ],
            },
          ],
        },
      },
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Entity/Table',
          left: 'OPR',
          right: '',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'Operation',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Name',
            left: 'OPR',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Description',
            left: 'System Operation',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Comment',
            left: 'System Operation [Calculated]',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Logical Only',
            left: 'true',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Only',
            left: 'false',
            right: '',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Theme',
            left: 'Corporate',
            right: '',
          },
        ],
        children: {
          'Attributes/Columns': [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: 'CD_OPR',
                right: '',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: 'Operation Code',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Datatype',
                  left: 'CHAR(8)',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Datatype',
                  left: 'CHAR(8) [Calculated]',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: 'CD_OPR',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Null Option',
                  left: 'Not Null',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Parent Domain',
                  left: 'String',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Description',
                  left: 'System Operation Code',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Comment',
                  left: 'System Operation Code [Calculated]',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Only',
                  left: 'false',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: 'false',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: 'Corporate',
                  right: '',
                },
              ],
            },
          ],
        },
      },
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Entity/Table',
          left: '',
          right: 'PRD',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: '',
            right: 'Product',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Name',
            left: '',
            right: 'PRD',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Description',
            left: '',
            right: 'Company Product',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Comment',
            left: '',
            right: 'Company Product [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Logical Only',
            left: '',
            right: 'true',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Only',
            left: '',
            right: 'false',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Theme',
            left: '',
            right: 'Corporate',
          },
        ],
        children: {
          'Attributes/Columns': [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: '',
                right: 'CD_PRD_XXX_XXX_XXX_XX_XX_XX',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: '',
                  right: 'Product Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Datatype',
                  left: '',
                  right: 'Integer',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Datatype',
                  left: '',
                  right: 'Integer [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: '',
                  right: 'CD_PRD',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Description',
                  left: '',
                  right: 'Company Product Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Comment',
                  left: '',
                  right: 'Company Product Code [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Only',
                  left: '',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: '',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: '',
                  right: 'Corporate',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Null Option',
                  left: '',
                  right: 'Not Null',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Parent Domain Very long name for property',
                  left: '',
                  right: 'Number',
                },
              ],
            },
          ],
        },
      },
      {
        id: {
          level: 3,
          spaces: 3 * INDENT_SIZE,
          type: 'Entity/Table',
          left: 'USU',
          right: 'USU',
        },
        properties: [
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Name',
            left: 'User [Calculated]',
            right: 'User [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Name',
            left: 'USU [Calculated]',
            right: 'USU [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Description',
            left: 'Company User',
            right: 'Company User',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Comment',
            left: 'Company User [Calculated]',
            right: 'Company User [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Logical Only',
            left: 'true',
            right: 'true',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Physical Only',
            left: 'false [Calculated]',
            right: 'false [Calculated]',
          },
          {
            level: 4,
            spaces: 4 * INDENT_SIZE,
            type: 'Theme',
            left: 'Corporate',
            right: 'Corporate',
          },
        ],
        children: {
          'Attributes/Columns': [
            {
              id: {
                level: 5,
                spaces: 5 * INDENT_SIZE,
                type: 'Attribute/Column',
                left: 'CD_USU',
                right: 'CD_USU',
              },
              properties: [
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Name',
                  left: 'User Code',
                  right: 'User Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Datatype',
                  left: 'CHAR(8)',
                  right: 'CHAR(8)',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Datatype',
                  left: 'CHAR(8) [Calculated]',
                  right: 'CHAR(8) [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Name',
                  left: 'CD_USU',
                  right: 'CD_USU',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Description',
                  left: 'Company User Code',
                  right: 'Company User Code',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Comment',
                  left: 'Company User Code [Calculated]',
                  right: 'Company User Code [Calculated]',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Logical Only',
                  left: 'false',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Physical Only',
                  left: 'false',
                  right: 'false',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Theme',
                  left: '',
                  right: '',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Null Option',
                  left: 'Not Null',
                  right: 'Not Null',
                },
                {
                  level: 6,
                  spaces: 6 * INDENT_SIZE,
                  type: 'Parent Domain',
                  left: 'String',
                  right: 'String',
                },
              ],
            },
          ],
        },
      },
    ],
  },
};
