import {
  type DiffRow,
  GROUPING_KEYWORDS,
  type GroupingKeyword,
  HEADERS_CONFIG,
  type HeaderKeyword,
  INDENT_SIZE,
  type ModelObject,
} from '../types.js';

/**
 * Parses raw HTML content from Erwin's Complete Compare reports into a structured ModelObject tree.
 *
 * @param html The raw HTML string generated by Erwin Data Modeler.
 * @returns A structured ModelObject representing the model hierarchy, or null if no model is found.
 */
export function parseErwinHtml(html: string): ModelObject | null {
  performance.mark('parse-start');
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  performance.mark('dom-parsed');

  const trs = doc.querySelectorAll('tbody tr');
  performance.mark('rows-queried');

  let rootModel: ModelObject | null = null;
  const stack: { obj: ModelObject; level: number; lastGrouping?: GroupingKeyword }[] = [];

  trs.forEach(tr => {
    const tds = tr.querySelectorAll('td');
    if (tds.length < 4) return;

    const objectTd = tds[0];
    const rawLeft = tds[1].textContent?.trim() || '';
    const rawRight = tds[3].textContent?.trim() || '';
    const rawTypeText = objectTd.textContent || '';
    const type = rawTypeText.trim();

    const leadingWhitespace = rawTypeText.match(/^[\s\u00a0]*/)?.[0] || '';
    const spaces = leadingWhitespace.length;
    const level = Math.floor(spaces / INDENT_SIZE);

    const isGrouping = GROUPING_KEYWORDS.includes(type as GroupingKeyword);
    const headerMatch = HEADERS_CONFIG.find(
      h => h.object === type && h.indentation.includes(spaces),
    );

    const diffRow: DiffRow = {
      level,
      spaces,
      type,
      left: rawLeft,
      right: rawRight,
    };

    if (headerMatch) {
      const newObj: ModelObject = {
        id: { ...diffRow, type: type as HeaderKeyword },
        properties: [],
        children: {},
      };

      if (!rootModel && type === 'Model') {
        rootModel = newObj;
        stack.push({ obj: rootModel, level });
      } else {
        // Pop stack until we find the parent (level < newObj level)
        // Note: Grouping rows are between parent and child.
        // Parent Level: L, Grouping Level: L+1, Child Level: L+2
        while (stack.length > 0 && stack[stack.length - 1].level >= level - 1) {
          stack.pop();
        }

        if (stack.length > 0) {
          const parent = stack[stack.length - 1];
          const grouping = parent.lastGrouping || ('Other' as GroupingKeyword);

          if (!parent.obj.children) parent.obj.children = {};
          if (!parent.obj.children[grouping]) parent.obj.children[grouping] = [];

          parent.obj.children[grouping].push(newObj);
          stack.push({ obj: newObj, level });
        }
      }
    } else if (isGrouping) {
      // Find current parent for this grouping (must be at level - 1)
      while (stack.length > 0 && stack[stack.length - 1].level >= level) {
        stack.pop();
      }
      if (stack.length > 0) {
        stack[stack.length - 1].lastGrouping = type as GroupingKeyword;
      }
    } else {
      // It's a property. Find current object (must be at level - 1)
      while (stack.length > 0 && stack[stack.length - 1].level >= level) {
        stack.pop();
      }
      if (stack.length > 0) {
        const currentObj = stack[stack.length - 1].obj;
        if (!currentObj.properties) currentObj.properties = [];
        currentObj.properties.push(diffRow);
      }
    }
  });

  performance.mark('parse-end');
  performance.measure('HTML-DOM Parsing', 'parse-start', 'dom-parsed');
  performance.measure('Rows Gathering', 'dom-parsed', 'rows-queried');
  performance.measure('Structure Building', 'rows-queried', 'parse-end');
  performance.measure('Total Parsing Time', 'parse-start', 'parse-end');

  const measures = performance.getEntriesByType('measure');
  console.table(
    measures.map(m => ({
      Task: m.name,
      'Time (ms)': m.duration.toFixed(2),
    })),
  );

  performance.clearMarks();
  performance.clearMeasures();

  return rootModel;
}
