import { type EnrichedDiffRow, INDENT_SIZE } from '../types.js';

/**
 * Parses raw HTML content from Erwin's Complete Compare reports.
 * Identifies indentation levels, change status, and object types.
 *
 * @param html The raw HTML string generated by Erwin Data Modeler.
 * @returns An array of EnrichedDiffRow representing the flat list of parsed objects and properties.
 */
export function parseErwinHtml(html: string): EnrichedDiffRow[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const rows: EnrichedDiffRow[] = [];
  const trs = doc.querySelectorAll('tbody tr');

  trs.forEach((tr, index) => {
    const tds = tr.querySelectorAll('td');
    if (tds.length < 4) return;

    const objectTd = tds[0];
    const rawLeft = tds[1].textContent?.trim() || '';
    const rawRight = tds[3].textContent?.trim() || '';

    // Strip [Calculated] for comparison
    const leftClean = rawLeft.replace(/\[Calculated\]/g, '').trim();
    const rightClean = rawRight.replace(/\[Calculated\]/g, '').trim();

    const rawTypeText = objectTd.textContent || '';
    const type = rawTypeText.trim();

    // Calculate indent: 3 spaces = 1 level.
    const leadingWhitespace = rawTypeText.match(/^[\s\u00a0]*/)?.[0] || '';
    const spaces = leadingWhitespace.length;
    const level = Math.floor(spaces / INDENT_SIZE);

    let change: 'I' | 'A' | 'E' | '' = '';
    if (leftClean && rightClean) {
      change = 'A';
    } else if (leftClean) {
      change = 'I';
    } else if (rightClean) {
      change = 'E';
    }

    // UDP highlighting for properties based on Erwin's internal naming conventions and depth
    const isUDP =
      ((type.startsWith('Entity.Physical.') || type.startsWith('Entity.Logical.')) &&
        spaces === 5 * INDENT_SIZE) ||
      ((type.startsWith('Attribute.Physical.') || type.startsWith('Attribute.Logical.')) &&
        spaces === 6 * INDENT_SIZE);

    rows.push({
      id: `row-${index}`,
      type,
      level,
      spaces,
      left: rawLeft,
      right: rawRight,
      change,
      prop: '',
      view: '',
      isUDP,
    });
  });

  return rows;
}
